'use strict';
const {test} = require('node:test');
const assert = require('node:assert/strict');
const E = require('../src/engine.js'), D = require('../src/data.js');
function setup(captain='ada', mode='journey', difficulty=0, seed=1729) { const meta=E.defaultMeta();meta.captains=Object.keys(D.captains);meta.settings.autoDecision=false;return {meta,s:E.newRun(meta,captain,mode,difficulty,seed)}; }
function eventChoice(s) { const info=E.eventInfo(s);return (info.choices.find(c=>c.id==='parts'&&c.enabled)||info.choices.find(c=>c.id==='pay'&&c.enabled)||info.choices.find(c=>c.id==='help'&&c.enabled)||info.choices.at(-1)).id; }
function leg(s,meta,id) { assert.ok(E.depart(s,id).ok);let steps=0;while(s.phase!=='station'&&!s.result&&steps++<100){if(s.phase==='event')assert.ok(E.resolveEvent(s,eventChoice(s)).ok);s.paused=false;E.tick(s,10,meta);}assert.ok(steps<100,'leg must terminate'); }
function cruise(s) { s.phase='travel';s.paused=false;s.segment={edgeId:'s-d',progress:0,eventDone:true};s.coal=100; }
test('station and pause freeze production, deadlines and decision',()=>{const {s,meta}=setup();E.beginDecision(s,'meal');const before=JSON.stringify(s);E.tick(s,30,meta);assert.equal(JSON.stringify(s),before);E.depart(s,'s-h');s.paused=true;const paused=JSON.stringify(s);E.tick(s,30,meta);assert.equal(JSON.stringify(s),paused);});
test('seeded simulation can be replayed after saving midway',()=>{const a=setup(),b=setup();E.depart(a.s,'s-r');E.depart(b.s,'s-r');E.tick(a.s,13,a.meta);E.tick(b.s,13,b.meta);const restore=JSON.parse(JSON.stringify(b.s));E.tick(a.s,10,a.meta);E.tick(restore,10,b.meta);assert.deepEqual(a.s,restore);});
test('trading enforces cash, market stock, capacity and positive quantity',()=>{const {s}=setup();assert.equal(E.trade(s,'grain','buy',-1).ok,false);s.cash=0;assert.equal(E.trade(s,'grain','buy',1).ok,false);s.cash=500;s.market.stock.grain=0;assert.equal(E.trade(s,'grain','buy',1).ok,false);s.market.stock.grain=20;assert.equal(E.trade(s,'grain','buy',8).ok,false);assert.ok(E.trade(s,'grain','buy',3).ok);assert.equal(s.cargo.grain,5);});
test('sale bonuses cannot create an infinite same-station buy/sell loop',()=>{const {s}=setup('clara');E.addArtifact(s,'ledger');s.decisions=['market'];s.cars[2].type='saloon';for(let i=0;i<30;i++){s.cash=1000;const before=s.cash;assert.ok(E.trade(s,'medicine','buy',1).ok);assert.ok(E.trade(s,'medicine','sell',1).ok);assert.ok(s.cash<before);}});
test('cold carriage prevents third-day spoilage',()=>{const a=setup(),b=setup();cruise(a.s);cruise(b.s);a.s.cargo.medicine=2;b.s.cargo.medicine=2;b.s.cars[0].type='cold';a.s.time=b.s.time=63.8;E.tick(a.s,.4,a.meta);E.tick(b.s,.4,b.meta);assert.equal(a.s.cargo.medicine,1);assert.equal(b.s.cargo.medicine,2);});
test('delivery is destination-gated, consumes cargo and pays exactly once',()=>{const {s,meta}=setup();const c=s.contractOffers[0];assert.ok(E.acceptContract(s,c.id).ok);assert.equal(E.deliver(s,c.id).ok,false);E.trade(s,'grain','buy',3);leg(s,meta,'s-h');assert.ok(E.deliver(s,c.id).ok);assert.equal(s.stats.delivered,1);const cash=s.cash;assert.equal(E.deliver(s,c.id).ok,false);assert.equal(s.cash,cash);});
test('escort reserves capacity and yields a story artifact on delivery',()=>{const {s,meta}=setup();const c=s.contractOffers.find(c=>c.type==='escort');E.acceptContract(s,c.id);assert.equal(E.metrics(s).used,3);leg(s,meta,'s-h');E.deliver(s,c.id);assert.equal(s.guests.length,0);assert.ok(s.artifacts.some(a=>a.id==='compass'));});
test('expired escort is removed and failure charged once',()=>{const {s,meta}=setup();const c=s.contractOffers.find(c=>c.type==='escort');E.acceptContract(s,c.id);s.contracts[0].due=1;cruise(s);s.time=31.9;E.tick(s,.3,meta);assert.equal(s.guests.length,0);assert.equal(s.stats.failed,1);E.tick(s,1,meta);assert.equal(s.stats.failed,1);});
test('bounty requires a defensive victory before payout',()=>{const {s}=setup();s.node='dawn';s.contracts=[{id:'bounty',name:'test',type:'bounty',to:'dawn',due:10,reward:75,goal:1,state:'active'}];assert.equal(E.deliver(s,'bounty').ok,false);s.stats.defended=1;assert.ok(E.deliver(s,'bounty').ok);});
test('removing capacity or last guard car cannot strand cargo or crew',()=>{const {s}=setup();s.cargo.grain=8;assert.equal(E.store(s,s.cars[0].uid).ok,false);s.cargo.grain=2;E.deploy(s,s.reserve[0].uid);E.hire(s,'cowboy');assert.equal(E.store(s,s.cars.at(-1).uid).ok,false);});
test('stored and merged car preserves training and workshop preparation',()=>{const {s}=setup();E.deploy(s,s.reserve[0].uid);const c=s.cars.at(-1);c.training=7;c.charge=2;const id=c.uid;assert.ok(E.store(s,id).ok);assert.ok(E.deploy(s,id).ok);assert.equal(c.training,7);s.reserve.push({...c,uid:'merge-copy',training:9,charge:1});assert.ok(E.merge(s,id).ok);assert.equal(c.level,2);assert.equal(c.training,9);assert.equal(c.charge,2);assert.equal(s.reserve.length,0);});
test('three-floor cap and recycling only affect reserve',()=>{const {s}=setup();s.cash=300;const c=s.cars[0];E.upgrade(s,c.uid);E.upgrade(s,c.uid);assert.equal(E.upgrade(s,c.uid).ok,false);assert.equal(c.level,3);assert.equal(E.recycle(s,c.uid).ok,false);const r=s.reserve[0],coal=s.coal;E.recycle(s,r.uid);assert.equal(s.coal,coal+2);});
test('tags count car instances rather than upgrade floors',()=>{const {s}=setup();s.cars[0].level=3;assert.equal(E.metrics(s).counts.trade,1);s.cars[2].type='cold';assert.equal(E.metrics(s).counts.trade,2);assert.equal(E.metrics(s).sale,.12);});
test('empty cars do not produce, boarding rotates each cycle',()=>{const {s,meta}=setup();s.basePassengers=1;cruise(s);E.tick(s,8.1,meta);assert.equal(s.cars[0].occupied,1);assert.equal(s.cars[1].occupied,0);E.tick(s,8,meta);assert.equal(s.cars[1].occupied,1);assert.equal(s.cars[0].occupied,0);});
test('workshop holds completed charge while full, then produces',()=>{const {s,meta}=setup();s.cars[2].type='workshop';s.basePassengers=12;s.cargo.grain=E.metrics(s).capacity;cruise(s);E.tick(s,25,meta);assert.ok(s.cars[2].charge>=3);assert.equal(s.cargo.parts,0);s.cargo.grain=0;E.tick(s,8,meta);assert.ok(s.cargo.parts>=1);});
test('decision prerequisites, completion, exclusion and cancellation refund',()=>{const {s,meta}=setup();s.cash=200;assert.equal(E.beginDecision(s,'fast').ok,false);E.beginDecision(s,'timetable');cruise(s);E.tick(s,23,meta);assert.ok(s.decisions.includes('timetable'));E.beginDecision(s,'fast');const before=s.cash;E.cancelDecision(s);assert.equal(s.cash,before+12);E.beginDecision(s,'rhythm');E.tick(s,30,meta);E.tick(s,5,meta);assert.ok(s.decisions.includes('rhythm'));assert.equal(E.beginDecision(s,'fast').ok,false);});
test('decision auto pause is honored during travel',()=>{const {s,meta}=setup();meta.settings.autoDecision=true;E.beginDecision(s,'meal');cruise(s);E.tick(s,25,meta);assert.equal(s.paused,true);assert.ok(s.decisions.includes('meal'));assert.ok(s.time<21);});
test('route queue auto departs only when arrival pause disabled',()=>{for(const autoArrival of [true,false]){const {s,meta}=setup();meta.settings.autoArrival=autoArrival;E.depart(s,'s-h');assert.ok(E.queueRoute(s,'h-p').ok);assert.equal(E.queueRoute(s,'s-r').ok,false);for(let i=0;i<12&&s.node==='sunset';i++){if(s.phase==='event')E.resolveEvent(s,eventChoice(s));E.tick(s,10,meta);}assert.equal(s.node,'harvest');assert.equal(s.phase,autoArrival?'station':'travel');assert.equal(s.queue.length,autoArrival?1:0);}});
test('events pause time and reject unaffordable choices without mutation',()=>{const {s,meta}=setup();s.phase='event';s.paused=true;s.segment={edgeId:'s-r',progress:.5,eventDone:true};s.event={type:'bandits'};s.cash=0;const before=JSON.stringify(s);E.tick(s,20,meta);assert.equal(JSON.stringify(s),before);assert.equal(E.resolveEvent(s,'pay').ok,false);assert.ok(E.resolveEvent(s,'cargo').ok);assert.equal(s.phase,'travel');assert.equal(s.cargo.grain,0);});
test('strike backlash persists until station rest',()=>{const {s}=setup();s.phase='event';s.event={type:'strike'};s.segment={edgeId:'s-r',progress:.5};const loss=E.metrics(s).dailyLoss;E.resolveEvent(s,'force');assert.ok(s.status.backlash===1);assert.ok(E.metrics(s).dailyLoss>loss+1);s.phase='station';E.service(s,'rest');assert.equal(s.status.backlash,0);});
test('rescue has a per-run limit and remains available when bankrupt',()=>{const {s}=setup();for(let i=0;i<2;i++){s.cash=0;s.coal=0;assert.ok(E.service(s,'rescue').ok);}s.cash=0;s.coal=0;assert.equal(E.service(s,'rescue').ok,false);});
test('Silas tension event and Clara three failures have distinct consequences',()=>{const a=setup('silas');a.s.tension=99;cruise(a.s);a.s.time=31.9;E.tick(a.s,.3,a.meta);assert.equal(a.s.tension,45);assert.equal(a.s.basePassengers,5);const b=setup('clara');b.s.stability={economy:0,trust:0,order:0};assert.equal(E.metrics(b.s).income,.6);assert.equal(E.beginDecision(b.s,'meal').ok,false);assert.equal(E.depart(b.s,'s-h').ok,false);assert.ok(E.governance(b.s,b.meta,'order').ok);assert.ok(E.depart(b.s,'s-h').ok);});
test('level growth and sheriff coal bonus are applied once per level',()=>{const {s}=setup('silas');const slots=s.baseSlots,coal=s.coal;E.gainXP(s,4);assert.equal(s.level,2);assert.equal(s.baseSlots,slots+1);assert.equal(s.coal,coal+3);});
test('artifact transformation changes speed only after 140 travel seconds',()=>{const {s,meta}=setup();E.addArtifact(s,'rusty');s.artifacts[0].age=139.8;assert.equal(E.metrics(s).speed,92);cruise(s);E.tick(s,.4,meta);assert.equal(E.metrics(s).speed,110);});
test('offer reroll costs escalate and newly locked pool changes next run only',()=>{const {s,meta}=setup();meta.coins=100;const pool=[...s.artifactPool];E.lockArtifact(meta,'clock');assert.deepEqual(s.artifactPool,pool);assert.ok(!E.newRun(meta).artifactPool.includes('clock'));E.makeOffer(s,meta);const c=s.coal;E.reroll(s,meta);E.reroll(s,meta);assert.equal(s.coal,c-5);assert.equal(s.offer.rerolls,2);});
test('exhausted artifact pool gives supplies instead of empty selection',()=>{const {s,meta}=setup();s.artifactPool=[];E.makeOffer(s,meta,'artifact');assert.equal(s.offer.choices[0].kind,'supplies');const coal=s.coal;E.selectOffer(s,0);assert.equal(s.coal,coal+5);});
test('page perks and inheritance can be disabled for next run',()=>{const {meta}=setup();meta.unlocked=Object.keys(D.artifacts);assert.equal(E.perks(meta),3);const a=E.newRun(meta).cash;meta.perksEnabled=false;assert.equal(E.newRun(meta).cash,a-45);meta.heritage={available:true,traits:['cash','fuel','room','heavy'],locks:['cash'],enabled:true};assert.equal(E.newRun(meta).cash,180);meta.coins=100;E.rollHeritage(meta);assert.ok(meta.heritage.traits.includes('cash'));assert.equal(meta.heritage.traits.length,4);meta.heritage.enabled=false;assert.equal(E.newRun(meta).cash,150);});
test('loss and repeated finish cannot duplicate permanent rewards',()=>{const {s,meta}=setup();cruise(s);s.morale=0;E.tick(s,.3,meta);assert.ok(s.result);const coins=meta.coins;assert.equal(E.finish(s,meta,true).ok,false);assert.equal(meta.coins,coins);assert.equal(meta.stats.runs,1);});
test('save validation accepts legitimate RNG, negative heritage and final histories',()=>{const {s,meta}=setup('clara', 'journey',0,4294967295);s.heritageEffects={cash:-20,speed:-5};assert.ok(E.validateSave({version:1,meta,run:s}).ok);E.finish(s,meta,false);assert.ok(E.validateSave({version:1,meta,run:s}).ok);});
test('malformed saves fail without throwing or prototype lookups',()=>{const {s,meta}=setup();for(const mutate of [p=>p.run.cars[0].type='constructor',p=>p.run.artifacts=[{id:'__proto__',age:1}],p=>p.run.cargo.grain=999,p=>p.meta.history=[{}],p=>delete p.run.stats,p=>p.run.rng=Infinity,p=>p.run.offer={choices:[{kind:'car',type:'bad'}]}]){const p=E.clone({version:1,meta,run:s});mutate(p);assert.equal(E.validateSave(p).ok,false);}assert.equal(E.validateSave(null).ok,false);});
test('all 3 captains and 4 difficulties can complete a funded, real journey',()=>{for(const captain of Object.keys(D.captains))for(let diff=0;diff<4;diff++){const {s,meta}=setup(captain,'journey',diff,531+diff);E.trade(s,'grain','buy',3);E.acceptContract(s,s.contractOffers[0].id);E.beginDecision(s,'meal');const path=['s-h','h-p','p-v','v-d'];for(const id of path){E.landmark(s,'supplies');if(s.coal<8)E.service(s,'coal');if(s.hull<70)E.service(s,'repair');if(captain==='clara')for(const key of ['economy','trust','order'])if(s.stability[key]<35)E.governance(s,meta,key);leg(s,meta,id);for(const c of s.contracts.filter(c=>c.state==='active'&&c.to===s.node))E.deliver(s,c.id);}assert.ok(!s.result,`${captain}/${diff} survives`);assert.ok(E.canFinish(s));E.endRun(s,meta);assert.equal(s.result.victory,true);assert.ok(E.validateSave({version:1,meta,run:s}).ok);}});
test('loop markets refresh and career objective remains optional after achievement',()=>{const {s,meta}=setup('ada','loop');for(const id of ['s-h','h-p','p-v','v-d','d-s']){E.landmark(s,'supplies');leg(s,meta,id);}assert.equal(s.laps,1);assert.equal(s.visitCounts.sunset,2);assert.ok(E.canFinish(s));assert.ok(s.contractOffers.length);s.mode='career';s.stats.delivered=4;s.cash=500;assert.ok(E.canFinish(s));assert.ok(E.depart(s,'s-h').ok);});
test('natural career completes contracts and cash target without injecting resources',()=>{const {s,meta}=setup('ada','career',0,19);E.beginDecision(s,'meal');let legs=0;const path=['s-h','h-p','p-v','v-d','d-s'];while(!E.canFinish(s)&&legs<20){E.landmark(s,'supplies');if(s.offer)E.skipOffer(s);const escort=s.contractOffers.find(c=>c.type==='escort');if(escort)E.acceptContract(s,escort.id);const delivery=s.contractOffers.find(c=>c.type==='delivery'&&c.good==='grain');if(delivery&&s.cash>70){const amount=Math.max(0,5-s.cargo.grain);if(!amount||E.trade(s,'grain','buy',amount).ok)E.acceptContract(s,delivery.id);}if(s.hull<50)E.service(s,'repair');leg(s,meta,path[legs%path.length]);for(const c of s.contracts.filter(c=>c.state==='active'&&c.to===s.node))E.deliver(s,c.id);assert.ok(!s.result);legs++;}assert.ok(legs<20);assert.ok(s.stats.delivered>=4);assert.ok(s.cash>=500);E.endRun(s,meta);assert.equal(s.result.victory,true);});
test('every artifact description has an operative hook, including arrival bell XP',()=>{const {s}=setup();const before=E.metrics(s);for(const id of Object.keys(D.artifacts))E.addArtifact(s,id);const m=E.metrics(s);assert.equal(s.artifacts.length,17);assert.ok(m.cycle<before.cycle);assert.ok(m.defense>before.defense);assert.ok(m.capacity>before.capacity);assert.ok(m.xp>before.xp);assert.ok(m.crit>0&&m.repeat>0);const single=setup();E.addArtifact(single.s,'bell');assert.equal(E.metrics(single.s).xp,3);});
test('a simultaneous decision completion and event preserves completion pause',()=>{const {s,meta}=setup();meta.settings.autoDecision=true;E.beginDecision(s,'meal');E.depart(s,'s-h');s.decision.elapsed=19.9;s.segment.progress=.479;E.tick(s,.2,meta);assert.equal(s.phase,'event');assert.equal(s.event.previousPause,true);E.resolveEvent(s,eventChoice(s));assert.equal(s.paused,true);});
test('representative routes across 60 seeds remain valid save states at every stop',()=>{for(let seed=1;seed<=60;seed++){const {s,meta}=setup(['ada','silas','clara'][seed%3],'journey',seed%4,seed);for(let i=0;i<8&&!s.result&&s.node!=='dawn';i++){E.landmark(s,'supplies');if(s.offer)E.skipOffer(s);const options=E.routes(s);leg(s,meta,options[seed%options.length].id);assert.ok(E.validateSave({version:1,meta,run:s}).ok,`seed ${seed}`);}assert.equal(s.node,'dawn');assert.ok(E.canFinish(s));}});
test('malformed nested records and runaway progress are rejected before restore',()=>{const {s,meta}=setup();for(const mutate of [p=>p.run.log=[null],p=>p.run.contribution={bad:null},p=>p.run.cycleProgress=999999,p=>p.run.market.stock={},p=>p.run.phase='result',p=>p.meta.settings.keys={pause:'invalid'}]){const p=E.clone({version:1,meta,run:s});mutate(p);assert.equal(E.validateSave(p).ok,false);}});
test('failed defense leaves a daily damage debt that station repair removes',()=>{const {s,meta}=setup();s.phase='event';s.event={type:'bandits'};s.segment={edgeId:'s-r',progress:.5,eventDone:true};s.rng=10000;E.resolveEvent(s,'defend');assert.equal(s.status.wound,1);const hull=s.hull;cruise(s);s.time=31.9;E.tick(s,.3,meta);assert.equal(s.hull,hull-1);s.phase='station';s.segment=null;assert.ok(E.service(s,'repair').ok);assert.equal(s.status.wound,0);assert.equal(s.hull,100);});
