"""Keep full-size portrait PNGs in source/ready and export small game WebPs.

Initial migration: python scripts/export_face_portraits.py --migrate
Later exports:      python scripts/export_face_portraits.py
Refresh file list:  python scripts/export_face_portraits.py --index-only
Style masters:      source/ready/<gemini|gpt>/<hero|monster>/*.png
Requires Pillow:    python -m pip install Pillow
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
from pathlib import Path

from PIL import Image, ImageChops


ROOT = Path(__file__).resolve().parents[1]
FACES = ROOT / "src/assets/art/faces"
SOURCE = FACES / "source/ready"
STYLES = ("gemini", "gpt")
GPT_MONSTERS = {"1201", "1202", "1203", "1401", "1402", "1403", "1450"}
SIZES = {"monster": 256, "hero": 320}


def game_path(master: Path, style: str | None = None) -> Path:
    """Shared ready masters keep their current owner; style-specific masters override it."""
    if style is None and master.parent.parent.name in STYLES:
        style = master.parent.parent.name
    if style is None:
        owners = [s for s in STYLES if (FACES / s / master.parent.name / f"{master.stem}.webp").exists()]
        style = owners[0] if len(owners) == 1 else (
            "gpt" if master.parent.name == "monster" and master.stem.split("_")[0] in GPT_MONSTERS else "gemini")
    if style not in STYLES:
        raise ValueError(f"Unknown portrait style: {style}")
    return FACES / style / master.parent.name / f"{master.stem}.webp"


def write_index() -> None:
    """The browser resolves missing variants without requesting missing image files."""
    files = {s: sorted(p.relative_to(FACES / s).as_posix()
                       for group in SIZES for p in (FACES / s / group).glob("*.webp")) for s in STYLES}
    output = FACES / "portrait_files.js"
    output.write_text("// Generated by scripts/export_face_portraits.py --index-only\n"
                      + "export const PORTRAIT_FILES = " + json.dumps(files, indent=2) + ";\n", encoding="utf-8")


def digest(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as file:
        for block in iter(lambda: file.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def migrate_sources() -> list[Path]:
    old_files = sorted(path for style in STYLES for group in SIZES for path in (FACES / style / group).glob("*.png"))
    for old in old_files:
        master = SOURCE / old.parent.parent.name / old.parent.name / old.name
        if master.exists() and digest(master) != digest(old):
            raise RuntimeError(f"Source differs from current game PNG: {master}")
    for old in old_files:
        master = SOURCE / old.parent.parent.name / old.parent.name / old.name
        master.parent.mkdir(parents=True, exist_ok=True)
        if not master.exists():
            shutil.copy2(old, master)
    return old_files


def export_one(master: Path, size: int, style: str | None = None, *, refresh_index: bool = True) -> tuple[Path, int]:
    with Image.open(master) as opened:
        if opened.width != opened.height or opened.width < size:
            raise ValueError(f"Expected square source at least {size}px: {master}")
        profile = opened.info.get("icc_profile")
        image = opened.convert("RGBA").resize((size, size), Image.Resampling.LANCZOS)

    # Avoid an unnecessary alpha channel for the few fully opaque portraits.
    pixels = image.convert("RGB") if image.getchannel("A").getextrema() == (255, 255) else image
    output = game_path(master, style)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(output.name + ".tmp")
    try:
        options = {"quality": 90, "method": 6}
        if profile:
            options["icc_profile"] = profile
        pixels.save(temporary, "WEBP", **options)
        with Image.open(temporary) as encoded:
            if encoded.size != (size, size) or encoded.format != "WEBP":
                raise RuntimeError(f"Invalid WebP export: {temporary}")
            if ImageChops.difference(image.getchannel("A"), encoded.convert("RGBA").getchannel("A")).getbbox():
                raise RuntimeError(f"Alpha changed in WebP export: {temporary}")
        os.replace(temporary, output)
    finally:
        temporary.unlink(missing_ok=True)
    if refresh_index:
        write_index()
    return output, output.stat().st_size


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--migrate", action="store_true", help="Copy old game PNGs to source/ready, then remove them after export")
    parser.add_argument("--style", choices=STYLES, help="Export into this style instead of the portrait's current folder")
    parser.add_argument("--index-only", action="store_true", help="Refresh the browser file list after manually adding WebPs")
    args = parser.parse_args()

    if args.index_only:
        write_index()
        return

    if not args.migrate and any(path for style in STYLES for group in SIZES for path in (FACES / style / group).glob("*.png")):
        parser.error("Game PNGs still exist; run with --migrate first")
    old_files = migrate_sources() if args.migrate else []
    # Shared masters first; explicit style versions win if both target the same file.
    styles = (args.style,) if args.style else STYLES
    masters = [path for base in (SOURCE, *(SOURCE / s for s in styles))
               for group in SIZES for path in sorted((base / group).glob("*.png"))]
    if not masters:
        parser.error(f"No portrait masters found in {SOURCE}")

    exported = [export_one(master, SIZES[master.parent.name], args.style, refresh_index=False) for master in masters]
    for old in old_files:
        master = SOURCE / old.parent.parent.name / old.parent.name / old.name
        output = game_path(master, args.style or old.parent.parent.name)
        if digest(master) != digest(old) or not output.is_file():
            raise RuntimeError(f"Keeping old PNG because migration could not be verified: {old}")
    for old in old_files:
        old.unlink()
    write_index()

    total = sum(size for _, size in exported)
    print(f"Exported {len(exported)} WebP portraits ({total:,} bytes); archived {len(old_files)} original PNGs")


if __name__ == "__main__":
    main()
